apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
    name: hello-world-service
spec:
  type: LoadBalancer
  selector:
    app: hello-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
