apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
    name: hello-world
spec:
  selector:
    app: hello-world
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
